name: Docker Image CI

on:
  push:
    branches: [ main ]
jobs:

  build:

    runs-on: ubuntu-latest
    env:
      DOCKER_PLATFORMS: linux/amd64

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      id: buildx
      with:
        install: true

    - name: Use Buildx
      run: docker buildx use ${{ steps.buildx.outputs.name }}

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build the Docker image
      run: |
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        docker buildx build --platform linux/amd64 -t kobrad/kobrad-stratum-bridge:latest --progress=plain --push .

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: kobradag/kobrad-stratum-bridge:latest
